---
title: "flat_utils.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(lubridate)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Get the date of the session from folder name

The date of the session is extracted from the name of the folder. This mode of operation assumes that all structures of files/folders names are standardized.
    
```{r function-get_date_from_folder_name}
#' Get the date of the session from folder name
#' 
#' @param path Character. Path of a folder containing the date inside its name.
#' 
#' @importFrom lubridate ymd
#' 
#' @return Date
#' 
#' @export
get_date_from_folder_name <- function(path){
  
  regmatches(
    path,
    regexpr("\\d{8}", path)
  ) |> 
  ymd()
    
}
```
  
```{r example-get_date_from_folder_name}
get_date_from_folder_name(
  path = "data/20240425"
)
```
  
```{r tests-get_date_from_folder_name}
test_that("get_date_from_folder_name works", {
  
  expect_equal(
    get_date_from_folder_name(
      path = "data/20240425"
    ), 
    as.Date("2024-04-25")
  )
  
  expect_equal(
    get_date_from_folder_name(
      path = "data/20240621"
    ), 
    as.Date("2024-06-21")
  )
  
})
```

# Predict if a given panelist likes a given fictional product or not
    
```{r function-predict_like}
#' Predict if a given panelist likes a given fictional product or not
#' 
#' @param data_coord_real Dataframe. Table with coordinates of real products.
#' @param data_grid Dataframe. Table with coordinates of fictional products (grid).
#' @param data_hedonic_large Dataframe. Table with hedonic data.
#' @param panelist_name Character. Name of the panelist.
#'
#' @importFrom tibble tibble
#' @importFrom stats lm predict.lm
#' 
#' @return A table with the coordinates of the fictional products. A 0 if the panelist does not like it, a 1 otherwise.
predict_like <- function(data_coord_real,
                         data_grid,
                         data_hedonic_large, 
                         panelist_name){
    
  # Combine the real coordinates and the liking score
  data_coord_real_liking <- tibble(
    dim1 = data_coord_real$dim1,
    dim2 = data_coord_real$dim2,
    dim1dim2 = data_coord_real$dim1dim2,
    liking_score = data_hedonic_large[[panelist_name]]
  )

  # Get the linear model to predict the liking score according to coordinates
  mod_predict_liking <- lm(
    formula = liking_score ~ dim1 + dim2 + dim1dim2, 
    data = as.data.frame(data_coord_real_liking)
  )

  # Predict the liking score for each point of the fictional grid
  predict_liking_grid <- predict.lm(
    object = mod_predict_liking, 
    newdata = data_grid, 
    type = "response"
  )
  
  # Find the mean of liking scores for the panelist
  mean_liking_panelist <- mean(data_coord_real_liking$liking_score)
  
  # Define if the panelist like or not
  # -- like = the predicted score is higher or = than the mean of the panelist
  predict_liking_grid <- as.numeric(predict_liking_grid >= mean_liking_panelist)
  # 0 means he/she does not like
  # 1 means he/she likes
  
  # Return the matrix
  res_grid_with_liking <- matrix(
    predict_liking_grid,
    nrow = length(unique(data_grid$dim1)), 
    ncol = length(unique(data_grid$dim2))
  )
  
  return(res_grid_with_liking)

}
```
  
```{r example-predict_like, eval=FALSE, echo=FALSE}
data("data_grid_toy")
data("data_hedonic_toy")
data("data_coord_real_toy")

data_hedonic_large_toy <- data_hedonic_toy |> 
  tidyr::pivot_wider(
    names_from = CONSUMER,
    values_from = SCORE
  )

predict_like(
  data_coord_real = data_coord_real_toy,
  data_grid = data_grid_toy,
  data_hedonic_large = data_hedonic_large_toy,
  panelist_name = "1"
)
```
  
```{r tests-predict_like}
test_that("predict_like works", {
  
  data("data_grid_toy")
  data("data_hedonic_toy")
  data("data_coord_real_toy")
  
  data_hedonic_large_toy <- data_hedonic_toy |>
    tidyr::pivot_wider(names_from = CONSUMER,
                       values_from = SCORE)
  
  # Unit test - panelist 1
  res_predict_like_panelist1 <- predict_like(
    data_coord_real = data_coord_real_toy,
    data_grid = data_grid_toy,
    data_hedonic_large = data_hedonic_large_toy,
    panelist_name = "1"
  )

  # long dput ----
  expect_equal(object = res_predict_like_panelist1[1:10, 1:10],
               expected = structure(
                 c(
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0
                 ),
                 dim = c(10L,
                         10L)
               ))
  # end of long dput ----
  
  # Unit test - panelist 27
  res_predict_like_panelist27 <- predict_like(
    data_coord_real = data_coord_real_toy,
    data_grid = data_grid_toy,
    data_hedonic_large = data_hedonic_large_toy,
    panelist_name = "27"
  )
  
  # long dput ----
  expect_equal(object = res_predict_like_panelist27[1:10, 1:10],
               expected = structure(
                 c(
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0,
                   0
                 ),
                 dim = c(10L,
                         10L)
               ))

  # end of long dput ----

})
```

# Create the report

```{r function-create_report}
#' Create the reproducible HTML sensory report
#'
#' @param date path_to_data_folder. Path to data folder.
#' @param session Character. ID of the sensory session.
#' @param products Character. Vector of products to include into the report.
#' @param output_dir Character. Path of the folder to save the report.
#' @param report_template Character. Path of the folder containing the report template.
#' 
#' @importFrom withr with_dir
#' @importFrom quarto quarto_render
#' 
#' @return A list with the folder and the file of the created report.
#' 
#' @export
create_report <- function(path_to_data_folder,
                          output_dir,
                          report_template = system.file(
                            "report",
                            package = "sensometrics"
                          )) {
  
  # Create the list of parameters
  list_param_report <- list(
    path_to_data_folder = path_to_data_folder
  )
  
  # Move the .qmd template into the temp directory
  fs::dir_copy(
    path = report_template,
    new_path = output_dir
  )

  # Render the report
  with_dir(
    file.path(output_dir, basename(report_template)), {
      quarto_render(
        input = "sensometrics_param_report.qmd",
        execute_params = list_param_report,
        quiet = TRUE
      )
  })
  
  return(
    list(
      output_dir_report = file.path(output_dir, basename(report_template)),
      output_file_report = "sensometrics_param_report.html"
    )
  )
  
}
```

```{r examples-create_report}
# Create a temporary directory
my_temp_dir <- tempfile()
dir.create(my_temp_dir)

# Create the sensory report
report <- create_report(
  path_to_data_folder = "data/20240425",
  output_dir = my_temp_dir
)

# Open the sensory report
browseURL(
  file.path(
    report$output_dir_report, 
    report$output_file_report
  )
)

# Delete temporary directory
unlink(my_temp_dir, recursive = TRUE)
```

```{r tests-create_report}
test_that("create_report works", {
  
  # Create temporary directory
  my_temp_dir <- tempfile()
  dir.create(my_temp_dir)
  
  # Create the sensory report
  report <- create_report(
    path_to_data_folder = "data/20240425",
    output_dir = my_temp_dir
  )
  
  # Check if the file exists
  expect_true(file.exists(
    file.path(
      report$output_dir_report,
      report$output_file_report
    )
  ))
  
  # Delete temporary directory
  unlink(my_temp_dir, recursive = TRUE)

})
```

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_utils.Rmd", 
  vignette_name = NA,
  check = FALSE
)
```

