---
title: "flat_perform_multidim_analysis.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(tidyr)
library(FactoMineR)
library(glue)
library(stringr)
library(plotly)
library(dplyr)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Transform the sensory data to a large format and perform a MCA

With `get_senso_mapping()`, you can perform the multidimensional analysis of sensory data. In practice, a Multiple Correspondence Analysis is realized (adapted for sorting task data). The graph of individuals (i.e. products) and attributes are displayed in an interactive format.

```{r function-get_senso_mapping}
#' Transform the sensory data to a large format and perform a MCA
#'
#' @param data_sensory Tibble. Table with the sensory data.
#' @param data_products Tibble. Table with the info about products.
#' @param axes Numeric. MCA axes to be plotted.
#' @param ... Other parameters of the FactoMineR::MCA() function.
#'
#' @importFrom tidyr pivot_wider
#' @importFrom dplyr arrange filter mutate pull group_by ungroup summarise
#' @importFrom FactoMineR MCA
#' @importFrom glue glue
#' @importFrom plotly plot_ly add_trace layout add_annotations
#' 
#' @return A list of 2 plotly graphs: the MCA ind plot and the MCA attributes
#' @export
get_senso_mapping <- function(data_sensory,
                              data_products,
                              axes = c(1, 2),
                              ...) {
  
  # Check parameters
  if (isFALSE(is.data.frame(data_sensory))) {
    stop("The data 'data_sensory' you provided is not a dataframe.")
  }
  
  if (isFALSE(is.data.frame(data_products))) {
    stop("The data 'data_products' you provided is not a dataframe.")
  }
  
  # Transform data to a PROD x ATTRIBUTE table
  data_large <- data_sensory |>
    pivot_wider(
      names_from = "consumer", 
      values_from = "group"
    ) |> 
    arrange(product)
    
  # Transform to dataframe and add rownames
  data_large <- as.data.frame(data_large)
  rownames(data_large) <- data_large$product
  data_large <- data_large[, -1]
  
  # Perform MCA
  res_mca <- MCA(
    X = data_large, 
    graph = FALSE, 
    ...
  )
  
  # Plot the map
  ## -- Find the products coordinates and take only the 2 first ones 
  coord_prod <- as.data.frame(res_mca$ind$coord[, axes])
  colnames(coord_prod) <- c("dim1", "dim2")
  
  ## -- Extra info about products
  vec_info <- data_products |> 
    filter(product %in% rownames(data_large)) |> 
    arrange(product) |> 
    mutate(text_tooltip = glue("Product {product}<br>{info}<br>{brand}")) |> 
    pull(text_tooltip)
  
  # Plot the attributes map
  ## -- Find the attributes x consumer coordinates and take only the 2 first one 
  coord_attr <- as.data.frame(res_mca$var$coord[, axes])
  colnames(coord_attr) <- c("dim1", "dim2")
  coord_attr[, "attribute"] <- rownames(coord_attr)
  
  ## -- Compute the barycenter of the attributes
  coord_attr <- coord_attr |> 
    mutate(attribute = str_remove_all(attribute, "\\d+_")) |> 
    group_by(attribute) |> 
    summarise(
      dim1 = mean(dim1),
      dim2 = mean(dim2)
    ) |> 
    ungroup()
  
  ## -- Plot
  inter_plot <- plot_ly(data = coord_prod) |>
    add_trace(
      x = ~ dim1 ,
      y = ~ dim2,
      hoverinfo = 'text',
      text = vec_info,
      type = "scatter",
      mode = "markers",
      marker = list(size = 6, color = "black"),
      showlegend = FALSE
    ) |>
    add_trace(
      x = ~ dim1,
      y = ~ dim2 + 0.05,
      text = rownames(coord_prod),
      type = "scatter",
      mode = "text",
      showlegend = FALSE, 
      hoverinfo = "none"
    ) |>
    add_trace(
      data = coord_attr,
      x = ~ dim1 ,
      y = ~ dim2,
      text = ~ attribute,
      type = "scatter", 
      mode = "text",
      textfont = list(color = "#55B4D2"), 
      showlegend = FALSE, 
      hoverinfo = "none"
    ) |> 
    layout(
      legend = list(
        orientation = "h",
        xanchor = "center",
        x = 0.5,
        y = -0.25
      ),
      title = list(
        text = "Sensory space",
        font = list(size = 14, color = "#444444")
      ),
      xaxis = list(
        zerolinecolor = "#D6D5D5",
        scaleanchor = "y",
        showgrid = FALSE,
        title = paste("Dim ", axes[1], " - ", round(res_mca$eig[axes[1], 2], 2), "%", sep = ""),
        titlefont = list(color = "#444444", size = 13),
        tickfont = list(size = 10, color = "#444444"),
        showline = TRUE,
        mirror = "ticks",
        linecolor = "#444444",
        linewidth = 1
      ),
      yaxis = list(
        zerolinecolor = "#D6D5D5",
        scaleanchor = "x",
        showgrid = FALSE,
        title = paste("Dim ", axes[2], " - ", round(res_mca$eig[axes[2], 2], 2), "%", sep = ""),
        titlefont = list(color = "#444444", size = 13),
        tickfont = list(size = 10, color = "#444444"),
        showline = TRUE,
        mirror = "ticks",
        linecolor = "#444444",
        linewidth = 1
      )
    )

  
  return(
    list(
      res_mca = res_mca,
      coord_prod = coord_prod,
      coord_attr = coord_attr,
      vec_info_tooltip = vec_info,
      inter_plot = inter_plot
    )
  )
  
}
```

```{r examples-get_senso_mapping, out.width='100%', out.height='100%'}
data("data_sensory_toy")
data("data_products_toy")

res_mapping <- get_senso_mapping(
  data_sensory = data_sensory_toy,
  data_products = data_products_toy
)

res_mapping$inter_plot
```

```{r tests-get_senso_mapping}
test_that("get_senso_mapping works", {

  data("data_sensory_toy")
  data("data_products_toy")
  
  plot_mapping <- get_senso_mapping(
    data_sensory = data_sensory_toy |> dplyr::rename_with(tolower),
    data_products = data_products_toy |> dplyr::rename_with(tolower)
  )
  
  expect_true(inherits(plot_mapping$inter_plot, "plotly"))

  # Test an error is the parameter is not a dataframe
  expect_error(
    object = get_senso_mapping(
      data_sensory = data_sensory_toy,
      data_products = 1), 
    regexp = "The data 'data_products' you provided is not a dataframe"
  )
  
  expect_error(
    object = get_senso_mapping(
      data_sensory = 1,
      data_products = data_products_toy), 
    regexp = "The data 'data_sensory' you provided is not a dataframe"
  )

})
```

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_perform_multidim_analysis.Rmd", 
  vignette_name = "Represent the sensory space on a map", 
  check = FALSE,
  overwrite = TRUE,
  open_vignette = FALSE
  )
```