# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand

test_that("get_date_from_file_name works", {
  
  expect_equal(
    get_date_from_file_name(
      file = "data/data_info_products_20240425.xlsx"
    ), 
    "20240425"
  )
  
  expect_equal(
    get_date_from_file_name(
      file = "data/data_info_products_20240621.xlsx"
    ), 
    "20240621"
  )
  
})
