# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand

test_that("create_report works", {
  
  # Create temporary directory
  my_temp_dir <- tempfile()
  dir.create(my_temp_dir)
  
  # Create the sensory report
  report <- create_report(
    path_to_data_folder = "data/20240425",
    output_dir = my_temp_dir
  )
  
  # Check if the file exists
  expect_true(file.exists(
    file.path(
      report$output_dir_report,
      report$output_file_report
    )
  ))
  
  # Delete temporary directory
  unlink(my_temp_dir, recursive = TRUE)

})
