# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand

test_that("get_date_from_folder_name works", {
  
  expect_equal(
    get_date_from_folder_name(
      path = "data/20240425"
    ), 
    as.Date("2024-04-25")
  )
  
  expect_equal(
    get_date_from_folder_name(
      path = "data/20240621"
    ), 
    as.Date("2024-06-21")
  )
  
})
