# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand

#' Create the reproducible HTML sensory report
#'
#' @param date path_to_data_folder. Path to data folder.
#' @param session Character. ID of the sensory session.
#' @param products Character. Vector of products to include into the report.
#' @param output_dir Character. Path of the folder to save the report.
#' @param report_template Character. Path of the folder containing the report template.
#' 
#' @importFrom withr with_dir
#' @importFrom quarto quarto_render
#' 
#' @return A list with the folder and the file of the created report.
#' 
#' @export
#' @examples
#' # Create a temporary directory
#' my_temp_dir <- tempfile()
#' dir.create(my_temp_dir)
#'
#' # Create the sensory report
#' report <- create_report(
#'   path_to_data_folder = "data/20240425",
#'   output_dir = my_temp_dir
#' )
#'
#' # Open the sensory report
#' browseURL(
#'   file.path(
#'     report$output_dir_report, 
#'     report$output_file_report
#'   )
#' )
#'
#' # Delete temporary directory
#' unlink(my_temp_dir, recursive = TRUE)
create_report <- function(path_to_data_folder,
                          output_dir,
                          report_template = system.file(
                            "report",
                            package = "sensometrics"
                          )) {
  
  # Create the list of parameters
  list_param_report <- list(
    path_to_data_folder = path_to_data_folder
  )
  
  # Move the .qmd template into the temp directory
  fs::dir_copy(
    path = report_template,
    new_path = output_dir
  )

  # Render the report
  with_dir(
    file.path(output_dir, basename(report_template)), {
      quarto_render(
        input = "sensometrics_param_report.qmd",
        execute_params = list_param_report,
        quiet = TRUE
      )
  })
  
  return(
    list(
      output_dir_report = file.path(output_dir, basename(report_template)),
      output_file_report = "sensometrics_param_report.html"
    )
  )
  
}
