# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand

#' Get the date of the session from folder name
#' 
#' @param path Character. Path of a folder containing the date inside its name.
#' 
#' @importFrom lubridate ymd
#' 
#' @return Date
#' 
#' @export
#' @examples
#' get_date_from_folder_name(
#'   path = "data/20240425"
#' )
get_date_from_folder_name <- function(path){
  
  regmatches(
    path,
    regexpr("\\d{8}", path)
  ) |> 
  ymd()
    
}
