# WARNING - Generated by {fusen} from dev/flat_utils.Rmd: do not edit by hand

#' Get the date of the session from file name
#' 
#' @param file Character. Path of a file containing the date inside its name.
#' 
#' @importFrom lubridate ymd
#' 
#' @return Date
#' 
#' @export
#' @examples
#' get_date_from_file_name(
#'   file = "data/data_info_products_20240425.xlsx"
#' )
get_date_from_file_name <- function(file){
  
  regmatches(
    basename(file),
    regexpr("\\d{8}", basename(file))
  ) |> 
  ymd()
    
}
