# WARNING - Generated by {fusen} from dev/flat_perform_multidim_analysis.Rmd: do not edit by hand

#' Transform the sensory data to a large format and perform a MCA
#'
#' @param data_sensory Tibble. Table with the sensory data.
#' @param data_products Tibble. Table with the info about products.
#' @param axes Numeric. MCA axes to be plotted.
#' @param ... Other parameters of the FactoMineR::MCA() function.
#'
#' @importFrom tidyr pivot_wider
#' @importFrom dplyr arrange filter mutate pull group_by ungroup summarise
#' @importFrom FactoMineR MCA
#' @importFrom glue glue
#' @importFrom plotly plot_ly add_trace layout add_annotations
#' 
#' @return A list of 2 plotly graphs: the MCA ind plot and the MCA attributes
#' @export
#' @examples
#' data("data_sensory_toy")
#' data("data_products_toy")
#'
#' res_mapping <- get_senso_mapping(
#'   data_sensory = data_sensory_toy,
#'   data_products = data_products_toy
#' )
#'
#' res_mapping$inter_plot
get_senso_mapping <- function(data_sensory,
                              data_products,
                              axes = c(1, 2),
                              ...) {
  
  # Check parameters
  if (isFALSE(is.data.frame(data_sensory))) {
    stop("The data 'data_sensory' you provided is not a dataframe.")
  }
  
  if (isFALSE(is.data.frame(data_products))) {
    stop("The data 'data_products' you provided is not a dataframe.")
  }
  
  # Transform data to a PROD x ATTRIBUTE table
  data_large <- data_sensory |>
    pivot_wider(
      names_from = "consumer", 
      values_from = "group"
    ) |> 
    arrange(product)
    
  # Transform to dataframe and add rownames
  data_large <- as.data.frame(data_large)
  rownames(data_large) <- data_large$product
  data_large <- data_large[, -1]
  
  # Perform MCA
  res_mca <- MCA(
    X = data_large, 
    graph = FALSE, 
    ...
  )
  
  # Plot the map
  ## -- Find the products coordinates and take only the 2 first ones 
  coord_prod <- as.data.frame(res_mca$ind$coord[, axes])
  colnames(coord_prod) <- c("dim1", "dim2")
  
  ## -- Extra info about products
  vec_info <- data_products |> 
    filter(product %in% rownames(data_large)) |> 
    arrange(product) |> 
    mutate(text_tooltip = glue("Product {product}<br>{info}<br>{brand}")) |> 
    pull(text_tooltip)
  
  # Plot the attributes map
  ## -- Find the attributes x consumer coordinates and take only the 2 first one 
  coord_attr <- as.data.frame(res_mca$var$coord[, axes])
  colnames(coord_attr) <- c("dim1", "dim2")
  coord_attr[, "attribute"] <- rownames(coord_attr)
  
  ## -- Compute the barycenter of the attributes
  coord_attr <- coord_attr |> 
    mutate(attribute = str_remove_all(attribute, "\\d+_")) |> 
    group_by(attribute) |> 
    summarise(
      dim1 = mean(dim1),
      dim2 = mean(dim2)
    ) |> 
    ungroup()
  
  ## -- Plot
  inter_plot <- plot_ly(data = coord_prod) |>
    add_trace(
      x = ~ dim1 ,
      y = ~ dim2,
      hoverinfo = 'text',
      text = vec_info,
      type = "scatter",
      mode = "markers",
      marker = list(size = 6, color = "black"),
      showlegend = FALSE
    ) |>
    add_trace(
      x = ~ dim1,
      y = ~ dim2 + 0.05,
      text = rownames(coord_prod),
      type = "scatter",
      mode = "text",
      showlegend = FALSE, 
      hoverinfo = "none"
    ) |>
    add_trace(
      data = coord_attr,
      x = ~ dim1 ,
      y = ~ dim2,
      text = ~ attribute,
      type = "scatter", 
      mode = "text",
      textfont = list(color = "#55B4D2"), 
      showlegend = FALSE, 
      hoverinfo = "none"
    ) |> 
    layout(
      legend = list(
        orientation = "h",
        xanchor = "center",
        x = 0.5,
        y = -0.25
      ),
      title = list(
        text = "Sensory space",
        font = list(size = 14, color = "#444444")
      ),
      xaxis = list(
        zerolinecolor = "#D6D5D5",
        scaleanchor = "y",
        showgrid = FALSE,
        title = paste("Dim ", axes[1], " - ", round(res_mca$eig[axes[1], 2], 2), "%", sep = ""),
        titlefont = list(color = "#444444", size = 13),
        tickfont = list(size = 10, color = "#444444"),
        showline = TRUE,
        mirror = "ticks",
        linecolor = "#444444",
        linewidth = 1
      ),
      yaxis = list(
        zerolinecolor = "#D6D5D5",
        scaleanchor = "x",
        showgrid = FALSE,
        title = paste("Dim ", axes[2], " - ", round(res_mca$eig[axes[2], 2], 2), "%", sep = ""),
        titlefont = list(color = "#444444", size = 13),
        tickfont = list(size = 10, color = "#444444"),
        showline = TRUE,
        mirror = "ticks",
        linecolor = "#444444",
        linewidth = 1
      )
    )

  
  return(
    list(
      res_mca = res_mca,
      coord_prod = coord_prod,
      coord_attr = coord_attr,
      vec_info_tooltip = vec_info,
      inter_plot = inter_plot
    )
  )
  
}
